### ISSUE TITLE
Two or more mutator tests for Message

### ISSUE THREAD

**Issue by sanjay920** [AJnad/CS1B#3]
There is only one test that you wrote. You should not put an if-else statement to demonstrate this. Instead follow this testing manner for mutators:

Print message. Set message using a valid string. Show that the message changed by printing it out. 

Print message2. Set message 2 using an invalid string. Show that message2 did not change because an invalid string was set on it (by printing out message 2 again).

Add any other comments, but if-else is not the way to prove that your tests are working. Take a look at your professor's test. Why not just mimic that?

**Comment by AJnad** [comment]
I cannot mimic my professor's tests because she stated in the instructions " Here is a sample run from my test (but you will have to imagine/deduce the source I used and create your own source for your testing, which will produce a different output)".
